## Switches
set_property PACKAGE_PIN V17 [get_ports {input[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[0]}]
set_property PACKAGE_PIN V16 [get_ports {input[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[1]}]
set_property PACKAGE_PIN W16 [get_ports {input[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[2]}]
set_property PACKAGE_PIN W17 [get_ports {input[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[3]}]
set_property PACKAGE_PIN W15 [get_ports {input[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[4]}]
set_property PACKAGE_PIN V15 [get_ports {input[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[5]}]
set_property PACKAGE_PIN W14 [get_ports {input[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[6]}]
set_property PACKAGE_PIN W13 [get_ports {input[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[7]}]
set_property PACKAGE_PIN R2 [get_ports {enIn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enIn}]
	
## LEDs
    set_property PACKAGE_PIN U16 [get_ports {output[0]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {output[0]}]
    set_property PACKAGE_PIN E19 [get_ports {output[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {output[1]}]
    set_property PACKAGE_PIN U19 [get_ports {output[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {output[2]}]
    set_property PACKAGE_PIN V19 [get_ports {GS}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {GS}]
    set_property PACKAGE_PIN W18 [get_ports {EO}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {EO}]