#set switches
set_property PACKAGE_PIN V17 [get_ports {SW1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW1}]
set_property PACKAGE_PIN V16 [get_ports {SW2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW2}]
set_property PACKAGE_PIN W16 [get_ports {SW3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW3}]
set_property PACKAGE_PIN W17 [get_ports {SW4}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SW4}]	

#set anodes
set_property PACKAGE_PIN U2 [get_ports {AN0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN0}]
set_property PACKAGE_PIN U4 [get_ports {AN1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN1}]
set_property PACKAGE_PIN V4 [get_ports {AN2}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN2}]
set_property PACKAGE_PIN W4 [get_ports {AN3}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AN3}]
	
#set segments
set_property PACKAGE_PIN W7 [get_ports {SegA}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegA}]
set_property PACKAGE_PIN W6 [get_ports {SegB}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegB}]
set_property PACKAGE_PIN U8 [get_ports {SegC}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegC}]
set_property PACKAGE_PIN V8 [get_ports {SegD}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegD}]
set_property PACKAGE_PIN U5 [get_ports {SegE}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegE}]
set_property PACKAGE_PIN V5 [get_ports {SegF}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegF}]
set_property PACKAGE_PIN U7 [get_ports {SegG}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SegG}]