# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.cache/wt [current_project]
set_property parent.project_path C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.srcs/sources_1/new/NANDgate.vhd
  C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.srcs/sources_1/new/Decoder.vhd
  C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.srcs/sources_1/new/logicF.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.srcs/constrs_1/new/decoder_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/zhenga6/CoCO/LogicFunction/LogicFunction.srcs/constrs_1/new/decoder_constraints.xdc]


synth_design -top logicF -part xc7a35tcpg236-1


write_checkpoint -force -noxdef logicF.dcp

catch { report_utilization -file logicF_utilization_synth.rpt -pb logicF_utilization_synth.pb }
