##switches
set_property PACKAGE_PIN V17 [get_ports {A}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A}]
set_property PACKAGE_PIN V16 [get_ports {B}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {B}]
set_property PACKAGE_PIN W16 [get_ports {C}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {C}]
set_property PACKAGE_PIN W17 [get_ports {D}]                
    set_property IOSTANDARD LVCMOS33 [get_ports {D}]
##LEDs
set_property PACKAGE_PIN U19 [get_ports {ABgtCD}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {ABgtCD}]
set_property PACKAGE_PIN E19 [get_ports {ABeqCD}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {ABeqCD}]
set_property PACKAGE_PIN U16 [get_ports {ABltCD}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {ABltCD}]